workflows:
  version: 2
  node-multi-build:
    jobs:
      - node-v8
      - node-latest
  e2e:
    jobs:
      - update-dependencies
    triggers:
      - schedule:
          cron: "*/5 * * * *" # On every Tuesday 09:00 (JST)
          filters:
            branches:
              only:
                - master

version: 2
jobs:
  base: &base
    docker:
      - image: circleci/node:latest
    working_directory: ~/repo
    steps:
      - checkout
      - restore_cache:
          keys:
          - v{{ .Environment.CIRCLECI_CACHE_VERSION }}-dependencies-{{ checksum "package-lock.json" }}
          - v{{ .Environment.CIRCLECI_CACHE_VERSION }}-dependencies-
      - run: npm install
      - run: npm run bootstrap
      - save_cache:
          paths:
            - node_modules
          key: v{{ .Environment.CIRCLECI_CACHE_VERSION }}-dependencies-{{ checksum "package-lock.json" }}
      - run: npm run lint
      - run: npm run flow
      - run: npm test
      - run: bash <(curl -s https://codecov.io/bash)
  node-v8:
    <<: *base
    docker:
      - image: node:8
  node-latest:
    <<: *base
    docker:
      - image: node:latest

  update-dependencies:
    <<: *base
    docker:
      - image: node:8
    steps:
      - checkout
      - run: npm install
      - run: npm run bootstrap
      - run: npm install -g hothouse
      - run: hothouse -t $GITHUB_TOKEN
