#!/usr/bin/env bash
set -eux

mkdir -p .release_note
npm run bootstrap

PREVIOUS_VERSION=$(jq -r .version package.json)
PREVIOUS_TAG=v$PREVIOUS_VERSION

lerna publish --force-publish=*

LATEST_VERSION=$(jq -r .version package.json)
LATEST_TAG=v$LATEST_VERSION

$(npm bin)/dotenv $(npm bin)/lerna-changelog -- \
  --from=$PREVIOUS_TAG \
  > .release_note/$LATEST_TAG.md

echo .release_note/$LATEST_TAG.md
hub release create -F .release_note/$LATEST_TAG.md $LATEST_TAG
